import Head from "next/head";
import TextField from "@mui/material/TextField";
import { AdapterLuxon } from "@mui/x-date-pickers/AdapterLuxon";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DateTimePicker } from "@mui/x-date-pickers/DateTimePicker";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>To-Do</a> App
        </h1>

        <p className={styles.description}>
          Get started by adding <code className={styles.code}>a new task</code>
        </p>
        <form>
          <TextField
            id="outlined-basic"
            label="Add a new task"
            variant="outlined"
            required
          />
          <LocalizationProvider dateAdapter={AdapterLuxon}>
            <DateTimePicker label="Start Date and Time" />
          </LocalizationProvider>
        </form>
        <br />
      </main>

      <footer className={styles.footer}>Powered by Hein Htet Aung</footer>
    </div>
  );
}
